### ISSUE TITLE
Methods to keep

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways-java-client#1]
VERSION 1:
- getXrefList
- findPathwaysByXref
- findPathwaysByText
- findPathwaysByLiterature
- listPathways
- getPathway - use [wp-assets repo](https://github.com/wikipathways/wikipathways-assets)
- getPathwayAs - use [wp-assets repo](https://github.com/wikipathways/wikipathways-assets)
- listOrganisms
- getPathwayInfo

VERSION 2:
- getOntologyTermsByPathway
- getPathwaysByParentOntologyTerm
- getPathwaysByOntologyTerm
- getCommunities
- getPathwaysByCommunity
- getCommunitiesByPathway
- getPathwayHistory

IGNORE THESE:
- getColoredPathway
- getCurationTagsByName
- getCurationTags
- getRecentChanges

**Comment by yihangx** [comment]
All methods are implemented.
